### ISSUE TITLE
help:  lint tool suggestion

### ISSUE THREAD

**Issue by ppd0705** [shopspring/decimal#294]
I make a same stupid error many times. the error is like the code below
```go
a := decimal.NewFromString("123")
b := decimal.NewFromString("345")
a.Sub(b)
// wanted:  a = a.Sub(b)
```
I often forget `a = `.  is there any lint tool for this situation  ?

**Comment by xiegeo** [comment]
govet has an unusedresult check. https://golangci-lint.run/usage/linters#govet

**Comment by ppd0705** [comment]
> govet has an unusedresult check. https://golangci-lint.run/usage/linters#govet

thanks for your reply.  the document is to simple to understand, do your have a config template ?
I tried the conf below, it doesn‘t work

```yaml
lint:
  govet:
    settings:
      unusedresult:
        stringmethods:
          - (github.com/shopspring/decimal.Decimal).Sub
```

**Comment by xiegeo** [comment]
@ppd0705 that looks like the funcs formate, stringmethods should just be `Sub`

``` yaml
lint:
  govet:
    settings:
      unusedresult:
        funcs:
          - (github.com/shopspring/decimal.Decimal).Sub
        stringmethods:
          - Sub
```
